#!/usr/bin/env python

import sys

from robot_process_supervisor.supervisor import SupervisorPlugin
from rqt_gui.main import Main

plugin = 'robot_process_supervisor'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
